BDIR=$(CURDIR)

BCLASS=player28

help:
	@echo 'Makefile for the evolcomp assignment                                      '
	@echo '                                                                          '
	@echo 'Usage:                                                                    '
	@echo '   make build                  build the code                             '
	@echo '   make test                   run the eval                               '
	@echo '                                                                          '

build:
	javac -cp contest.jar $(BCLASS).java Matrix.java Vector.java
	jar cmf MainClass.txt submission.jar $(BCLASS)*.class Matrix.class Vector.class

test:
	# java -jar testrun.jar -submission=$(BCLASS) -evaluation=BentCigarFunction -seed=1
	# java -jar testrun.jar -submission=$(BCLASS) -evaluation=SchaffersEvaluation -seed=1
	java -jar testrun.jar -submission=$(BCLASS) -evaluation=KatsuuraEvaluation -seed=1

.PHONY: help test build
