BDIR=$(CURDIR)

BCLASS=player28

help:
	@echo 'Makefile for the evolcomp assignment                                      '
	@echo '                                                                          '
	@echo 'Usage:                                                                    '
	@echo '   make build                  build the code                             '
	@echo '   make test                   run the eval                               '
	@echo '                                                                          '

build:
	javac -cp contest.jar $(BCLASS).java
	jar cmf MainClass.txt submission.jar $(BCLASS)*.class

test:
	java -jar testrun.jar -submission=$(BCLASS) -evaluation=BentCigarFunction -seed=1

.PHONY: help test build
