BDIR=$(CURDIR)

BCLASS=player28

help:
	@echo 'Makefile for the evolcomp assignment                                      '
	@echo '                                                                          '
	@echo 'Usage:                                                                    '
	@echo '   make build                  build the code                             '
	@echo '   make test                   run the eval                               '
	@echo '                                                                          '

build:
	javac -cp contest.jar $(BCLASS).java Jama/*.java Jama/util/*java
	jar cmf MainClass.txt submission.jar $(BCLASS)*.class Jama/*class Jama/util/*class

test:
	java -Dverbose=false -jar testrun.jar -submission=$(BCLASS) -evaluation=BentCigarFunction -seed=50
	java -Dverbose=false -jar testrun.jar -submission=$(BCLASS) -evaluation=SchaffersEvaluation -seed=7
	java -Dverbose=false -jar testrun.jar -submission=$(BCLASS) -evaluation=KatsuuraEvaluation -seed=5

.PHONY: help test build
